# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter build tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dart-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '2.10.5'
          channel: 'stable'
          cache: true

        # get dependencies
      - run: flutter pub get
        # copy env file
      - run: cp lib/environment.dart.example lib/environment.dart
      # lint the code
      - run: dart analyze --fatal-infos

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '2.10.5'
          channel: 'stable'
          cache: true

        # get dependencies
      - run: flutter pub get
        # copy env file
      - run: cp lib/environment.dart.example lib/environment.dart
      # build app
      - run: flutter build apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '2.10.5'
          channel: 'stable'
          architecture: x64
          cache: true

        # get dependencies
      - run: flutter pub get
        # copy env file
      - run: cp lib/environment.dart.example lib/environment.dart
      # build app
      - run: flutter build ios --release --no-codesign

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '2.10.5'
          channel: 'stable'
          cache: true

        # get dependencies
      - run: flutter pub get
        # copy env file
      - run: cp lib/environment.dart.example lib/environment.dart
      # build app
      - run: flutter build web


